/* Automatically generated by configure */
#ifndef COMPONENTS_CONFIG_H
#define COMPONENTS_CONFIG_H

extern papi_vector_t _perf_event_vector;
extern papi_vector_t _perf_event_uncore_vector;

struct papi_vectors *_papi_hwd[] = {
   &_perf_event_vector,
   &_perf_event_uncore_vector,
   NULL
};

#endif
